export const dataEmployer = [
  {
    KODE: 'KAR00001',
    NAMA: 'ANDI AGUS',
    ALAMAT: 'KP. PANGRADIN RT/RW 02/02. JASINGA',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'089680477455",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Kepala Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00002',
    NAMA: 'AHMAD ISMAIL',
    ALAMAT: 'DESA TANJUNGSARI RT/RW/001/002\n\n\n\nTANJUNGSARI, ROWOSARI',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'089635542065",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00003',
    NAMA: 'SUDARMAN',
    ALAMAT: 'PINANG RANTI NO.10 RT/RW 001/001\n\n\n\nPINANGRANTI, MAKASAR',
    KOTA: 'JAKARTA',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'085697880526",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Kepala Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00004',
    NAMA: 'AMRON HAKIM',
    ALAMAT: 'DK. GINTUNG RT/RW 003/008, SIMA MOGA',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'083115303228",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00005',
    NAMA: 'ARIEF ABDUL GHANI',
    ALAMAT: 'LUWUNGGEDE RT/RW 006/002 \n\n\n\nLUWUNGGEDE, TANJUNG',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'089630724420",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00006',
    NAMA: 'WANDA WIGUNA',
    ALAMAT: 'KP. SERPONGRT/RW. 001/007, SERPONG',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'089684336085",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00007',
    NAMA: 'MANSUR SAH',
    ALAMAT: 'KP. CINANGNENG RT/RW. 001/002\n\n\n\nCIHIDEUNGUDIK, CIAMPEA',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'087788068551",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Kepala Body Repair',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00008',
    NAMA: 'ANGGA TAMA PRADHIAS MUKTY',
    ALAMAT: 'KLITIK, RT/RW 004/005, KISMANTORO',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'082264315991",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Service Advisor',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00009',
    NAMA: 'JUNAEDI',
    ALAMAT: 'CILUBANGI LEBAK RT/RW 002/001\n\n\n\nSITU GEDE, BOGOR BARAT',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'0895375729396",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Service Advisor',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00010',
    NAMA: 'HERWIN SUPRIYANSAH SAHPUTRA',
    ALAMAT: 'JL. LESTARI II RT/RW 002/005\n\n\n\nCURUG, BOJONGSARI',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'081294639755",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00011',
    NAMA: 'M. ABDUL AZIZ',
    ALAMAT: 'CINANAS RT/RW 001/002\n\n\n\nBANTARKAWUNG',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'083144629480",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00012',
    NAMA: 'RAFLI ARDANA MAULANA',
    ALAMAT: 'KP. TANJAKAN CINANGNENG\n\n\n\nRT/RW 005/006 CIBANTENG, CIMPEA',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'081514024961",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00013',
    NAMA: 'WAHYU NUGROHO',
    ALAMAT: 'AREMAN, RT/RW 004/008\n\n\n\nTUGU, CIMANGGIS',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'087714529149",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Spare Part',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00014',
    NAMA: 'REZA WAHYU PRATAMA',
    ALAMAT: 'BOJONGSARI, RT/RW 002/010\n\n\n\nBOJONGSARI',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'089508775839",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Spare Part',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00015',
    NAMA: 'FITRI YANTO',
    ALAMAT: 'KLURAHAN RT002/RW012, \n\n\nSUKOHARJO',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'088802685249",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00017',
    NAMA: 'JAKA SETIAWAN',
    ALAMAT: 'KP. SAWAH RT/RW 003/003 \n\n\n\nLEUWINUTUG, CITEUREUP',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'085863253369",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Body Repair',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00018',
    NAMA: 'ALI',
    ALAMAT: 'KP. CIPEUSING RT/RW 003/005\n\n\n\nCIMERANG, PURABAYA',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'083815925224",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Body Repair',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00019',
    NAMA: 'SOBANDI',
    ALAMAT: 'KP. CIKADU RT/RW 006/002 \n\n\n\nBOJONGTIPAR, JAMPANG TENGAH',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'085695373610",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Body Repair',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00020',
    NAMA: 'DADANG',
    ALAMAT: 'KP. CIPEUSING RT/RW 003/005\n\n\n\nCIMERANG, PURUBAYA',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'083127149096",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Body Repair',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00021',
    NAMA: 'MUHAMMAD ALI AKBAR',
    ALAMAT: 'JL. H.USA RT/RW 001/003 CISEENG\n\n\n.',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'082298625087",
    EMAIL: '',
    STATUS: 'Tidak Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00022',
    NAMA: 'ARBI AHMAD PAIJI',
    ALAMAT: 'KP. CIPESING RT002/005 CIMERANG, \n\n\nPURABAYA',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': '',
    EMAIL: '',
    STATUS: 'Tidak Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Body Repair',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00023',
    NAMA: 'MUHAMAD TIRTA',
    ALAMAT: 'Pacing Selatan Rt/Rw 004/002 Dewisari, Rengasdengklok.',
    KOTA: 'BOGOR',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'089535839450",
    EMAIL: '',
    STATUS: 'Tidak Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Body Repair',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00025',
    NAMA: 'ZAIN FAIZIL HAQ',
    ALAMAT: 'KLITIK RT/RW, 004/005, MIRI KISMANTORO',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'081212007868",
    EMAIL: '',
    STATUS: 'Tidak Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00027',
    NAMA: 'ABAH GAMA',
    ALAMAT: '',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': '',
    EMAIL: '',
    STATUS: 'Tidak Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Body Repair',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00028',
    NAMA: 'IRVAN KURNIAWAN',
    ALAMAT: 'MERTODRANAN, RT/RW 001/001 PASAR KLIWON',
    KOTA: 'DEPOK',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': '',
    EMAIL: '',
    STATUS: 'Tidak Tetap',
    'TGL. MASUK': '',
    JABATAN: 'Staff',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00029',
    NAMA: 'DHIKA NOVERIS',
    ALAMAT: 'NGARAN RT/RW 03/04 NGASINAN, GRABAG',
    KOTA: 'MAGELANG',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'085786828933",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '4/21/25',
    JABATAN: 'Front Desk',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00030',
    NAMA: 'EDOARDO FROS HANSEN SAWEHO',
    ALAMAT: 'BANYUMUDAL SIKUCING RT/RW. 005/003, BANYUMUDAL,  MOGA, PEMALANG',
    KOTA: 'PEMALANG',
    PROVINSI: 'JAWA TENGAH',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'083161124986",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '5/12/25',
    JABATAN: 'Mekanik',
    'STATUS PIT (True/False)': 'TRUE',
  },
  {
    KODE: 'KAR00031',
    NAMA: 'ADITIYA MAULANA',
    ALAMAT: 'CURUG RT/RW. 002/004, CURUG, BOJONGSARI, DEPOK',
    KOTA: 'DEPOK',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. HP': "'08818815105",
    EMAIL: '',
    STATUS: 'Tetap',
    'TGL. MASUK': '4/14/25',
    JABATAN: 'KANTIN',
    'STATUS PIT (True/False)': 'TRUE',
  },
];
