export const supplierData = [
  {
    KODE: 'SUP00015',
    NAMA: 'DAVIN MOTOR [WAWAN]',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00016',
    NAMA: 'BRAVO BENGKEL',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00017',
    NAMA: 'KIKI JAYA SPAREPART',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00018',
    NAMA: 'BAMBANG MOTOR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00019',
    NAMA: 'DODI LARIS MATIC',
    ALAMAT: 'BENGKEL LARIS MATIC',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': "'081311050198",
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00020',
    NAMA: 'YULI COPOTAN',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00021',
    NAMA: 'TRI STAR MOTOR',
    ALAMAT: 'BLOK M',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00024',
    NAMA: 'MAMAN KACA',
    ALAMAT: 'PONDOK CABE',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00025',
    NAMA: 'MITRA BERSAUDARA',
    ALAMAT: 'JL RAYA PANTAI INDAH KAPUK',
    KOTA: 'JAKARTA',
    PROVINSI: 'DKI',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00026',
    NAMA: 'PT TOYIB BROTHER',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00027',
    NAMA: 'FANS AUTO MATIC',
    ALAMAT: 'BOGOR',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00028',
    NAMA: 'GROSIR OLI HARGA PARTAI',
    ALAMAT: 'TANGERANG SELATAN',
    KOTA: 'TANGERANG',
    PROVINSI: 'BANTEN',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00029',
    NAMA: 'HAIDAR COPOTAN',
    ALAMAT: 'PARUNG',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00030',
    NAMA: 'ANEKA BAUT',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00031',
    NAMA: 'MAHESWARI FOOD',
    ALAMAT: 'TEBET JAKARTA',
    KOTA: 'JAKARTA',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': "'08872437347",
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00032',
    NAMA: 'FIRMANDA BAUT',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00033',
    NAMA: 'PT PERTAMINA [PERSERO]',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00034',
    NAMA: 'GRAND NEW AUTOMOTIVE',
    ALAMAT: 'BEKASI',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00035',
    NAMA: 'SULIS COPOTAN',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00036',
    NAMA: 'FREDY NOFANDY',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00037',
    NAMA: 'RAFI MOBIL [ OM ADE SRS ]',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': "'081398240429",
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00039',
    NAMA: 'MAPAG SEJAHTERA MOTOR',
    ALAMAT: 'PASAR MOBIL KEMAYORAN BLOK Y NO,11',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00040',
    NAMA: 'RAMA MOTOR',
    ALAMAT: 'RUKO PERKANTORAN DUTA MAS FATMAWATI BLOK D1 NO.3',
    KOTA: 'JAKARTA SELATAN',
    PROVINSI: 'JAKARTA SELATAN',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00041',
    NAMA: 'RUDI COPOTAN',
    ALAMAT: 'GN.SINDUR',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00042',
    NAMA: 'PT ANUGERAH ABADI DAYA CEMERLANG',
    ALAMAT: 'JAKARTA TIMUR',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00043',
    NAMA: 'BTC BOJONG SARI',
    ALAMAT: 'DEPOK',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': "'081285796159",
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00044',
    NAMA: 'BTC CITRALIKE',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00045',
    NAMA: 'TAUFIK',
    ALAMAT: 'CIAMPEA',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00046',
    NAMA: 'TEH INDRI',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': "'081298215910",
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00047',
    NAMA: 'PT VITECHINDO PRKASA',
    ALAMAT: 'JAKARTA TIMUR',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00048',
    NAMA: 'ATEK MOTOR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00049',
    NAMA: 'DARMAWAN POWER STEERING',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00050',
    NAMA: 'INDO KIMIA JAYA',
    ALAMAT: 'JALAN TEUKU NYAK ARIEF NO.1 GROGOL SELATAN KEBAYORAN LAMA',
    KOTA: 'JAKARTA',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00051',
    NAMA: 'RIZKY COPOTAN BOGOR',
    ALAMAT: 'BOGOR',
    KOTA: 'BOGOR',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': "'089508543889",
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00052',
    NAMA: 'BKS PART SOLO KARANGANYAR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00053',
    NAMA: 'HERU D FIVE',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00054',
    NAMA: 'SAHABAT MOTOR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00055',
    NAMA: 'RAHAYU SERVICE',
    ALAMAT: 'Jl. Raya Muchtar Perempatan Pengasinan Sawangan',
    KOTA: 'DEPOK',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': "'081212635356",
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00057',
    NAMA: 'BUBUT FAMILY JAYA',
    ALAMAT: 'JL RAYA CURUG BOJONGSARI-DEPOK',
    KOTA: 'DEPOK',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': "'083153190705",
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00058',
    NAMA: 'SYAHIRA CARWASH',
    ALAMAT: 'JL RAYA MUCHTAR  NO 48 SAWANGAN LAMA DEPOK',
    KOTA: 'DEPOK',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00059',
    NAMA: 'WAHONO AUTO PART',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00060',
    NAMA: 'PT CAHAYA KENCANA KARYAWISESA',
    ALAMAT: 'CIPUTAT',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00061',
    NAMA: 'PT BQUIK OTOMOTIF INDONESIA',
    ALAMAT: 'JL RAYA MUCHTAR, SAWANGAN LAMA',
    KOTA: 'DEPOK',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00062',
    NAMA: 'LARIS JAYA MOTOR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00063',
    NAMA: 'SILICON BUDI ZONE',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00064',
    NAMA: 'MUNADI TEKNIK',
    ALAMAT: 'JL BOJONGSARI LAMA NO 117',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': "'085947758154",
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00065',
    NAMA: 'EL AUTO',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00066',
    NAMA: 'RIO JAYA AC',
    ALAMAT: 'JL RAYA BOJONGSARI DEPAN KANTOR POS',
    KOTA: 'DEPOK',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00067',
    NAMA: 'NO LIMIT',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00068',
    NAMA: 'IDA BAGUS',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00069',
    NAMA: 'HARAPAN JAYA',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00070',
    NAMA: 'AUTO MATIC CENTER',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00071',
    NAMA: 'CITRA MOTOR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00072',
    NAMA: 'ARJUNA POWER STEERING',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00073',
    NAMA: 'SURYA JAYA MOTOR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00074',
    NAMA: 'KINO JAYA FILM',
    ALAMAT: 'DEPOK',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': "'08128591222",
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00075',
    NAMA: 'LIN KARYA AC',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00076',
    NAMA: 'DANI SIKAT KAWAT',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00077',
    NAMA: 'PD CABE [MANSYUR]',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00078',
    NAMA: 'MBA TARNI',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00079',
    NAMA: 'KARYA MOTOR',
    ALAMAT: 'JL RAYA BOJONGSARI NO 26',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': "'081310375598",
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00080',
    NAMA: 'BENGKEL SUKSES MOTOR BLOCK M',
    ALAMAT: 'BLOK M JAKSEL',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00081',
    NAMA: 'MAS DURI',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP00082',
    NAMA: 'RUDI [BUSHING RACK]',
    ALAMAT: 'JAKARTA UTARA',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUP0015',
    NAMA: 'TOPIK COPOTAN',
    ALAMAT: 'BOGOR',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 001',
    NAMA: 'DELTA MOTOR',
    ALAMAT: 'GN.SINDUR',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 002',
    NAMA: 'MANDALA MOTOR',
    ALAMAT: 'PS.ONDERDIL PONDOK CABE NO.49',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 003',
    NAMA: 'NEW CHANDRA MOTOR',
    ALAMAT: 'RUKO CITRA SAWANGAN',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 004',
    NAMA: 'BNA AUTOMOTIVE',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 005',
    NAMA: 'TONI HONDA',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 006',
    NAMA: 'CV.TRITUNGGAL SELARAS',
    ALAMAT: 'RUKO PONDOK CABE MUTIARA BLOK B NO 19',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': "'0217424649",
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 007',
    NAMA: 'PT.GARUDA PETRO PERKASA',
    ALAMAT: 'JL.RAYA CITRA GARDEN 8 NO 05 RT 04 RW 08 KALI DERES',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 008',
    NAMA: 'TOKPED',
    ALAMAT: 'TOKO PEDIA',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 009',
    NAMA: 'BUDI',
    ALAMAT: 'JL RAYA CINANGKA NO 9',
    KOTA: 'DEPOK',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 010',
    NAMA: 'ACIM BATTERY',
    ALAMAT: 'JL.RAYA MUCHTAR SAWANGAN DEPOK [PERTIGAAN PENGASINAN] NO.91',
    KOTA: 'DEPOK',
    PROVINSI: 'JAWA BARAT',
    'KODE POS': '',
    'NO. TELEPON': "'082113075512",
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 011',
    NAMA: 'SOLIHIN',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 012',
    NAMA: 'AJAT VRIVA',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 013',
    NAMA: 'GALERI MOTOR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
  {
    KODE: 'SUPLIER 014',
    NAMA: 'MANG ADE RADIATOR',
    ALAMAT: '',
    KOTA: '',
    PROVINSI: '',
    'KODE POS': '',
    'NO. TELEPON': '',
    'NO. FAKS': '',
    'NO. HP': '',
    EMAIL: '',
    WEBSITE: '',
  },
];
